### ISSUE TITLE
Headless installation

### ISSUE THREAD

**Issue by fallingcats** [Rudd-O/hassmpris_agent#2]
Is there any way to use this agent on a headless system?

**Comment by Rudd-O** [comment]
I believe so, as long as there is a shared D-Bus session — the players and the agent are in the same session.  The agent doesn't, to my knowledge, make connections to the X server.  IF IT DOES when you , and you can get a traceback, post it in this ticket.

Please note that autostart of the agent is done via D-Bus desktop autostart files currently.  This won't work on boot — you have to manually run the agent within your headless session.

**Comment by fallingcats** [comment]
> I believe so, as long as there is a shared D-Bus session — the players and the agent are in the same session.  The agent doesn't, to my knowledge, make connections to the X server.  IF IT DOES when you , and you can get a traceback, post it in this ticket.
> 
> Please note that autostart of the agent is done via D-Bus desktop autostart files currently.  This won't work on boot — you have to manually run the agent within your headless session.

The problem is that I don't know how to start it, and the documentation assumes I have X11 & GTK4 installed to run the configuration script

**Comment by Rudd-O** [comment]
Oh yes silly me I forgot to include instructions.

https://github.com/Rudd-O/hassmpris_agent/blob/master/README.md#manually-eg-in-a-headless-scenario

It seems to work on my side so I'm closing this ticket.  Thanks for the report.
