### ISSUE TITLE
Installation on a Raspberry Pi requires GTK 4.0, current version is 4.1

### ISSUE THREAD

**Issue by whatisthisUT** [Rudd-O/hassmpris_agent#7]
I installed hassmpris_agent on the Raspberry Pi 4 (Debian Bookworm, released 4-July-2024).
Trying to run hassmpris-settings returns an error saying it requires GTK 4.0.
I couldn't find a way to install the 4.0 version and can't run the software.

**Comment by Rudd-O** [comment]
Can you please show me the backtrace?  I'm happy to fix it but I need to be able to see what's going on.

**Comment by Rudd-O** [comment]
Can you please provide a traceback?  Otherwise I will have to close this.

**Comment by whatisthisUT** [comment]
Hi, I apologise, but I had to use another solution at that time and at the moment I don't have access to a Raspberry PI.

**Comment by Rudd-O** [comment]
OK.  If someone else reports it with a traceback, I will be very glad to reopen this.
